import pandas as pd
import plotly.express as px

data = pd.read_csv('DataSets//Supply Chain Analysis//supply_chain_data.csv')

print(data.head())
print(data.info())

fig1 = px.scatter(data, x='Price', y='Revenue generated', color='Product type', trendline='ols', title='Revenue generated by Products across Product types')
fig1.show()#Scatter plot for Revenue Generated across product prices.

sales_data = data.groupby('Product type')['Number of products sold'].sum().reset_index()
print(sales_data)#Data grouped by Product type with values of number of products sold.

fig2 = px.pie(sales_data, values='Number of products sold', names='Product type', hole=0.5, title='Sales by product type', color_discrete_sequence=px.colors.qualitative.Plotly[4:7])
fig2.update_traces(textposition = 'inside', textinfo='percent+label')
fig2.show()#Pie chart for analyzing number of products sold across Product types.

revenue_generated = data.groupby(['Shipping carriers','Product type'])['Revenue generated', 'Shipping costs'].sum().reset_index()
print(revenue_generated)#Revenue and Shipping costs by Shipping modes and product types

fig3_1 = px.bar(revenue_generated, x='Product type', y='Revenue generated', color='Shipping carriers', color_discrete_sequence=px.colors.qualitative.Plotly[4:7], title='Revenue generated across Product types')
fig3_1.show()#Bar plot for revenue generated for different product types

fig3_2 = px.bar(revenue_generated, color='Product type', y='Shipping costs', x='Shipping carriers', color_discrete_sequence=px.colors.qualitative.Vivid[4:7], title='Manufacturing costs across Product types')
fig3_2.show()

fig4 = px.bar_polar(data, theta='SKU', r='Revenue generated', title='Revenue Generated by SKU', color='Product type', color_discrete_sequence=px.colors.qualitative.Prism[4:7]).update_layout(polar_hole=0.5)
fig4.show()

fig5 = px.bar_polar(data, theta='SKU', r='Stock levels', title='Stock levels by SKU', color='Product type', color_discrete_sequence=px.colors.qualitative.Prism[4:7]).update_layout(polar_hole=0.5)
fig5.show()

fig6 = px.bar(data, x='Shipping carriers', y='Shipping costs', color_discrete_sequence=['lightcoral'], title='Shipping Costs by Carrier')
fig6.show()

fig7= px.pie(data, values='Costs', names='Transportation modes', title='Cost Distribution by Transportation Mode',hole=0.5,color_discrete_sequence=px.colors.qualitative.Light24[5:9])
fig7.show()

defect_rates_by_product = data.groupby('Product type')['Defect rates'].mean().reset_index()
print(defect_rates_by_product)

fig8 = px.bar(defect_rates_by_product, x='Product type', y='Defect rates',title='Average Defect Rates by Product Type')
fig8.show()